export const USERS = [
  "Admin",
  "Regular User",
  "Manager",
  "Employee",
  "Customer",
  "Guest",
  "Supervisor",
  "Team Lead",
  "Consultant",
  "Contractor",
  "Vendor",
];

export const HEADER = [
  { title: "Tutor", isChevronIcon: true },
  { title: "Date of Buying", isChevronIcon: true },
  { title: "Country", isChevronIcon: true },
  { title: "Subscription Plan", isChevronIcon: false },
  { title: "User", isChevronIcon: false },
];

export const TABLEDATA = [
  {
    tutor: "John Doe",
    dateOfBuying: "2024-07-10",
    price: "$49.99",
    subscriptionPlan: "Premium",
    user: "Alice",
    country: "USA",
  },
  {
    tutor: "Jane Smith",
    dateOfBuying: "2024-07-09",
    price: "$29.99",
    subscriptionPlan: "Standard",
    user: "Bob",
    country: "Canada",
  },
  {
    tutor: "Sam Brown",
    dateOfBuying: "2024-07-08",
    price: "$19.99",
    subscriptionPlan: "Basic",
    user: "Eve",
    country: "UK",
  },
  {
    tutor: "Lucy Green",
    dateOfBuying: "2024-07-07",
    price: "$39.99",
    subscriptionPlan: "Standard",
    user: "Charlie",
    country: "Australia",
  },
  {
    tutor: "Mark Blue",
    dateOfBuying: "2024-07-06",
    price: "$59.99",
    subscriptionPlan: "Premium",
    user: "David",
    country: "USA",
  },
  {
    tutor: "Anna White",
    dateOfBuying: "2024-07-05",
    price: "$24.99",
    subscriptionPlan: "Basic",
    user: "Emma",
    country: "France",
  },
  {
    tutor: "Mike Black",
    dateOfBuying: "2024-07-04",
    price: "$34.99",
    subscriptionPlan: "Standard",
    user: "George",
    country: "Germany",
  },
  {
    tutor: "Nina Brown",
    dateOfBuying: "2024-07-03",
    price: "$29.99",
    subscriptionPlan: "Standard",
    user: "Hannah",
    country: "Italy",
  },
  {
    tutor: "Oscar Grey",
    dateOfBuying: "2024-07-02",
    price: "$44.99",
    subscriptionPlan: "Premium",
    user: "Ivy",
    country: "Spain",
  },
  {
    tutor: "Paul White",
    dateOfBuying: "2024-07-01",
    price: "$19.99",
    subscriptionPlan: "Basic",
    user: "Jack",
    country: "Netherlands",
  },
];
